# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e09adbcfe18ddb2eef53672515a3c72f8addf1ed3f3369a8f37017931816b7e0448a1dade7e04cc6ca6bf4245a190ebe8dbe76ab2ff4f2441eae4396f4078227

test:
  secret_key_base: 9933230fbb9cc9f5534d7e24211e27c1382e6d28e638d5e9afa0f9eaa5129e85f9a2ea94e46f7038ee4995e1e5de6a676f19758625543890657a0c074775d1ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
